---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: production
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./environments/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  validation: client

