---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: development
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./environments/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: development
  validation: client

